### ISSUE TITLE
cleartext http traffic to not permitted

### ISSUE THREAD

**Issue by raj-bhagat** [applibgroup/AppCrashTracker#5]
##Description
The bug is that when I try to use an HTTP connection it throws an error, "Buffer Write Exception", when I try to POST some values to my jsonServer. So to find the real error I debugged the code and found that it was throwing an exception, "java.io.IOException: Cleartext HTTP traffic to not permitted". In android, it can be fixed by adding "useCleartextTraffic=”true” ", but I don't know the fix for the same in harmony OS.  

##To Reproduce
1. Go to  **src/main/resources/base/element/string.json**
2. Replace the **value** key with any HTTP connection type where **name** key is  **_url_**
3. Run the application
4. Crash the application with uncaughtException.
5. See error

##Expected behavior
The expected behavior was that the a json file was uploaded to the server with all the information that was selected.

##Desktop
-OS: Windows 10
-DevEco Studio 2.1.0.501
-Harmony OS SDK  5

##Device Information
-Device: MatePad Pro
-OS: Harmony OS

##Additional context
Here I am hosting json server on my local machine and connecting it to internet using ngrok. I have already tested POST and GET method in postman.

**Comment by kanaksony** [comment]
Can you try adding the following code in your config.json?

```
 "deviceConfig": {
    "default": {
      "network": {
        "cleartextTraffic": true,
        "usesClearText": true
      }
    }
  }
```

**Comment by raj-bhagat** [comment]
@kanaksony It worked for me after removing "usesClearText": true
